name: Create and publish Docker image to CapRover

# Requires the following Action secrets to be set in your GitHub repo:
# - CAPROVER_APP_TOKEN
# - CAPROVER_SERVER_URL

on:
  push:
    branches: ["main"]

env:
  BRANCH_NAME: ${{ github.ref_name || github.head_ref }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_FILE_NAME: ./Dockerfile
  IMAGE_NAME: ${{ github.repository }}
  CAPROVER_APP: alldjango-web

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ${{ env.DOCKER_FILE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy image to CapRover
        run: |
          docker run caprover/cli-caprover:latest caprover deploy --host ${{ secrets.CAPROVER_SERVER_URL }} --appToken ${{ secrets.CAPROVER_APP_TOKEN }} --appName ${{ env.CAPROVER_APP }} --imageName ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
        shell: bash
