on: [push]

jobs:
  deploy_to_caprover:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: adamghill/deploy-to-caprover@v2
        with:
          caprover-app-name: alldjango-web
